name: Lint HTML

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "docs/**"
      - "fix/**"
      - "chore/**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer djLint
        run: pip install djlint

      - name: Lancer le lint HTML
        run: python -m djlint index.html --profile=html --lint
